apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service
  namespace: ns1
data:
  services.product.url: "http://product-service.ns2.svc.cluster.local:8080"
  welcome.message: "hahahahahahah"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: app
      containers:
        - name: main
          image: docker.io/kutzhang/study-springcloud-order-service:20230116231639
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ns1
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080